/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedUserRouteImport } from './routes/_authenticated/_user'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/_user/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminProdiRouteImport } from './routes/_authenticated/admin/prodi'
import { Route as AuthenticatedAdminKnowledgeBaseRouteImport } from './routes/_authenticated/admin/knowledge-base'
import { Route as AuthenticatedAdminChatHistoryIndexRouteImport } from './routes/_authenticated/admin/chat-history.index'
import { Route as AuthenticatedAdminChatHistorySessionIdRouteImport } from './routes/_authenticated/admin/chat-history.$sessionId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserRoute = AuthenticatedUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUserRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProdiRoute = AuthenticatedAdminProdiRouteImport.update({
  id: '/prodi',
  path: '/prodi',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKnowledgeBaseRoute =
  AuthenticatedAdminKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChatHistoryIndexRoute =
  AuthenticatedAdminChatHistoryIndexRouteImport.update({
    id: '/chat-history/',
    path: '/chat-history/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChatHistorySessionIdRoute =
  AuthenticatedAdminChatHistorySessionIdRouteImport.update({
    id: '/chat-history/$sessionId',
    path: '/chat-history/$sessionId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedUserIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/knowledge-base': typeof AuthenticatedAdminKnowledgeBaseRoute
  '/admin/prodi': typeof AuthenticatedAdminProdiRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/chat-history/$sessionId': typeof AuthenticatedAdminChatHistorySessionIdRoute
  '/admin/chat-history/': typeof AuthenticatedAdminChatHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedUserIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/knowledge-base': typeof AuthenticatedAdminKnowledgeBaseRoute
  '/admin/prodi': typeof AuthenticatedAdminProdiRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/chat-history/$sessionId': typeof AuthenticatedAdminChatHistorySessionIdRoute
  '/admin/chat-history': typeof AuthenticatedAdminChatHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/_user': typeof AuthenticatedUserRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/knowledge-base': typeof AuthenticatedAdminKnowledgeBaseRoute
  '/_authenticated/admin/prodi': typeof AuthenticatedAdminProdiRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/_user/': typeof AuthenticatedUserIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/chat-history/$sessionId': typeof AuthenticatedAdminChatHistorySessionIdRoute
  '/_authenticated/admin/chat-history/': typeof AuthenticatedAdminChatHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/admin'
    | '/admin/knowledge-base'
    | '/admin/prodi'
    | '/admin/users'
    | '/admin/'
    | '/admin/chat-history/$sessionId'
    | '/admin/chat-history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/admin/knowledge-base'
    | '/admin/prodi'
    | '/admin/users'
    | '/admin'
    | '/admin/chat-history/$sessionId'
    | '/admin/chat-history'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/verify-otp'
    | '/_authenticated/_user'
    | '/_authenticated/admin'
    | '/_authenticated/admin/knowledge-base'
    | '/_authenticated/admin/prodi'
    | '/_authenticated/admin/users'
    | '/_authenticated/_user/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/chat-history/$sessionId'
    | '/_authenticated/admin/chat-history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_user': {
      id: '/_authenticated/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_user/': {
      id: '/_authenticated/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prodi': {
      id: '/_authenticated/admin/prodi'
      path: '/prodi'
      fullPath: '/admin/prodi'
      preLoaderRoute: typeof AuthenticatedAdminProdiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/knowledge-base': {
      id: '/_authenticated/admin/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/admin/knowledge-base'
      preLoaderRoute: typeof AuthenticatedAdminKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chat-history/': {
      id: '/_authenticated/admin/chat-history/'
      path: '/chat-history'
      fullPath: '/admin/chat-history/'
      preLoaderRoute: typeof AuthenticatedAdminChatHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chat-history/$sessionId': {
      id: '/_authenticated/admin/chat-history/$sessionId'
      path: '/chat-history/$sessionId'
      fullPath: '/admin/chat-history/$sessionId'
      preLoaderRoute: typeof AuthenticatedAdminChatHistorySessionIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedUserRouteChildren {
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
}

const AuthenticatedUserRouteChildren: AuthenticatedUserRouteChildren = {
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
}

const AuthenticatedUserRouteWithChildren =
  AuthenticatedUserRoute._addFileChildren(AuthenticatedUserRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminKnowledgeBaseRoute: typeof AuthenticatedAdminKnowledgeBaseRoute
  AuthenticatedAdminProdiRoute: typeof AuthenticatedAdminProdiRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminChatHistorySessionIdRoute: typeof AuthenticatedAdminChatHistorySessionIdRoute
  AuthenticatedAdminChatHistoryIndexRoute: typeof AuthenticatedAdminChatHistoryIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminKnowledgeBaseRoute: AuthenticatedAdminKnowledgeBaseRoute,
  AuthenticatedAdminProdiRoute: AuthenticatedAdminProdiRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminChatHistorySessionIdRoute:
    AuthenticatedAdminChatHistorySessionIdRoute,
  AuthenticatedAdminChatHistoryIndexRoute:
    AuthenticatedAdminChatHistoryIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedUserRoute: typeof AuthenticatedUserRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUserRoute: AuthenticatedUserRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
